### ISSUE TITLE
How do you create an array using your library?

### ISSUE THREAD

**Issue by TotteKarlsson** [Jacajack/mkjson#1]
Say I'm having a list of thousand strings in say a vector\<string\> and want to create the json:

{
"mystrings" : ["string1", "string2"... ]
}

Is that possible?

Thanks for a nice library!

**Comment by Jacajack** [comment]
Currently creating arbitrarily-sized JSON arrays is not possible. I may add this as an extension some time, though.

In C++, however, solution to your problem is pretty simple:
```cpp
std::vector<std::string> v{ "Hello", "world", "!" };

std::string s = std::string( "[\"" ) + std::accumulate( v.begin( ), v.end( ), std::string( "" ),
	[]( const std::string &l, const std::string &r )
	{
		return l + ( l.empty( ) ? "" : "\", \"" ) + r;
	} ) + "\"]";
```

Also, if you're working on some large C++ project, there's no reason to stick with `mkjson`, which is meant for C and simple applications. Maybe you should try a real C++ library. Personally, I like jsoncpp: https://github.com/open-source-parsers/jsoncpp
